apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: backend
  namespace: web
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: web
        image: blaize/backend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000