apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: frontend
  namespace: web
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: web
        image: blaize/frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80