apiVersion: v1
kind: Pod
metadata:
  name: secretpod
spec:
  containers:
  - name: secretpod
    image: busybox
    args:
    - sleep
    - "1000000"    
    volumeMounts:
    - name: secretvol
      mountPath: "/etc/secret"
      readOnly: true
  volumes:
  - name: secretvol
    secret:
      secretName: app-login