apiVersion: v1
kind: Pod
metadata:
  name: secretpod
spec:
  containers:
  - name: secretpod
    image: busybox
    args:
    - sleep
    - "1000000"    
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: app-login
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: app-login
            key: password