apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: blaizenfsv3.blob.core.windows.net
    path: "/blaizenfsv3/nfsv3"
  mountOptions:
    - nolock
    - vers=3
    - sec=sys
    - proto=tcp