apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.1.0.4
    path: "/vol1"
  mountOptions:
    - rw
    - hard
    - rsize=1048576
    - wsize=1048576
    - vers=3
    - tcp