apiVersion: v1
kind: Service
metadata:
  name: keen
  labels:
    app: keen
spec:
  ports:
  - port: 80
    targetPort: 80  
    name: http
  selector:
    app: keen
  type: LoadBalancer  
---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: keen
spec:
  selector:
    matchLabels:
      app: keen
  replicas: 1
  template:
    metadata:
      labels:
        app: keen
    spec:
      containers:
      - name: keen-kontainer
        image: blaize/keen
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/dos"
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: volume
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: volume
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-blobfuse-flexvol
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blobfuse-flexvol
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "azure/blobfuse"
    secretRef:
      name: blobfusecreds
    options:
      container: dosgames
      tmppath: /tmp/blobfuse
      mountoptions: "--file-cache-timeout-in-seconds=120"      