apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: blaizenfsv3.blob.core.windows.net
    path: "/blaizenfsv3/dosshare"
  mountOptions:
    - hard
    - nolock
    - nfsvers=3    