apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.240.0.35
    path: "/blaizenfs/dos"
  mountOptions:
    - vers=4
    - minorversion=1
    - sec=sys  
